selam millet benim adim yunus ilk nereden baslamaliyim bilmiyom yani normal bir hayatım var tabi normal se kendimi tanitmakla basliyim ben sanliurfa/surucluyum ama osmaniyede yasışıyorum sizleride tanimak isterim
